### ISSUE TITLE
See if parallelStream() APIs will yield better performance for hydra-server

### ISSUE THREAD

**Issue by paragchandra** [PandoraMedia/hydra#19]
Currently we're using the sequential `stream()` API to build our test blacklists (in `PartitionService.buildTestBlacklist`). However, it may be more performant to use `parallelStream()`. The concern is that parallelizing this operation may not yield any performance improvement - we're not currently seeing blacklist generation as a bottleneck - but it may uncover some subtle concurrency problems. Therefore, we'll have to test this extensively over multiple runs.

**Comment by jguerra** [comment]
I wouldn't expect to see any noticeable performance improvement here. This step simply combines each partitions already calculated blacklist into a single set
