### ISSUE TITLE
Integrating the plugin with Android application fails

### ISSUE THREAD

**Issue by sonahovhannisyan** [PandoraMedia/hydra#2]
Hi,

Project's configuration fails when integrating Hydra plugin with this message
`Could not get unknown property 'sourceSets' for task ':integrationTest' of type org.gradle.api.tasks.testing.Test.`

Here is the build.gradle file.
```
buildscript {
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0-alpha13'
        classpath 'com.pandora.hydra:hydra-gradle-plugin:1.6.5'
    }
}

apply plugin: 'com.pandora.hydra'

task integrationTest(type: Test) {
    minHeapSize = "1g"
    maxHeapSize = "6g"

    outputs.upToDateWhen { false }
    testClassesDirs = sourceSets.integrationTest.output.classesDirs
    classpath = sourceSets.integrationTest.runtimeClasspath

    ignoreFailures true

    testLogging {
        events 'passed', 'failed'
    }

    maxParallelForks = 10
}

hydra {
    balancedTests = ['integrationTest']
}
```

Tried with both Gradle 4.10.1 and 5.1-20181022112637+0000.

**Comment by jguerra** [comment]
The `sourceSets` configuration is added by the java plugin. If you are using the android plugin I think you would need something like `android.sourceSets.test.java.sourceFiles` instead

**Comment by alex-dubrouski** [comment]
Thanks for reporting this issue. I have created Android project with empty view and added Hydra plugin. Unfortunately, Android plugin has it's own implementations of all classes including `DefaultAndroidSourceSet` which does not have runtime classpath, and test task `AndroidUnitTest`, thus currently Hydra is not compatible with Android builds out of the box.
I will add a task to implement integration with Android as our internal team is also interested in it.
I am sorry for disappointing you.

**Comment by sonahovhannisyan** [comment]
I see. Np, I'll try it out on java project then and integrate on android when it's ready. Thanks for your kind reply and explanation.

**Comment by alex-dubrouski** [comment]
I am sorry for delay, end of a year rush in the office.
I created a branch `android-support` and added custom implementation, which supports AndroidUnitTest tasks. You can pull the branch, publish to local Maven repo (I added plugin for publishing) with `./gradlew publishToM` and test. Here is the example of Android module build file (poject was created in AndroidStudio, using empty app template with 1 module named `test1`):
```
buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
        google()
    }
    dependencies {
        classpath 'com.pandora.hydra:hydra-gradle-plugin:1.6.6-SNAPSHOT'
    }
}

apply plugin: 'com.android.application'
//Enabling parallel threads
project.tasks.withType(Test) {
    maxParallelForks = Runtime.runtime.availableProcessors()
}
//Please make sure Hydra is applied after Android plugin
apply plugin: 'com.pandora.hydra'
hydra {
    balancedTests = ['testReleaseUnitTest']
    balanceThreads = true
}

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.example.adubrouski.test1"
        minSdkVersion 15
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}
``` 
In this example I balance the tests for `release` flavor (`testReleaseUnitTest`), but you can try balancing multiple flavors. This version depends on `com.android.tools.build:gradle:3.2.0` version of a plugin
I will try to add support for AndroidTests but it might take some time.

**Comment by sonahovhannisyan** [comment]
Thanks @alex-dubrouski for implementing android support. I've tried it out, but running the balancing task fails because of missing env variable. Here is my build scan. 
https://scans.gradle.com/s/bn55xgajc2tdm
In `Configuration.java` I saw that there are some other environment variables I need to configure. Would you hint me what variables are necessary to have and with what values? Do I need to configure something else?

**Comment by alex-dubrouski** [comment]
You need 3 environmental variables to be set:
```
HYDRA_HOST_LIST="comma-separated-list-of-nodes"
HYDRA_SERVER="backend.address"
JOB_NAME="jenkins-job-name"
```
We have this in readme, but let me give you more details:
HYDRA_HOST_LIST - is a list of hosts running unit tests, framework designed to run thousands of tests on a cluster of physical hosts, so running on one node (i.e. `HYDRA_HOST_LIST="localhost"`) lowers the value. Though you can still enable tests multithreading and balance between threads.
HYDRA_SERVER - host name where back end part is deployed. The whole idea of the framework is to save test execution times, thus plugin can rebalance tests between hosts and threads on next run lowering overall execution time
JOB_NAME - usually set by Jenkins, but you can set it manually. It is kind of a unique key which helps us to distinguish different builds and their results.

**Comment by alex-dubrouski** [comment]
Good day,
I am sorry for delay, we had quite tough end of the year. We added support for Android unit tests with help of our internal Mobile Ops team and migrating internal Android builds to Hydra now. Documentation is updated, I am going to release 1.6.7 soon, but you can test the code in master branch right now
