### ISSUE TITLE
Custom JVM Options Not Honored

### ISSUE THREAD

**Issue by paragchandra** [PandoraMedia/hydra#7]
I've noticed that a custom JVM option I specify in my 'normal' test task (`-noverify`) doesn't seem to be honored by the Hydra-enabled counterpart task, because I get errors like the one shown below for a couple of my tests. I looked into the code, and it seems BalancedTestConfigurer isn't making a call to `setJvmArgs()` in order to copy the JVM options from the source test task.

`java.lang.VerifyError: Expecting a stackmap frame at branch target 174
Exception Details:
  Location:
    com/moat/analytics/mobile/pndr/l.<clinit>()V @30: ldc
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: b800 524b b800 194c b800 194d b800 194e
    0x0000010: b800 193a 04b8 0019 3a05 2a05 0454 1207
    0x0000020: 3a06 1906 1203 04bd 000e 5903 b200 1753
    0x0000030: b600 1b3a 0719 0612 0406 bd00 0e59 0312
    0x0000040: 1153 5904 1206 5359 0512 0553 b600 1b3a
    0x0000050: 0819 0612 0104 bd00 0e59 0312 0553 b600
    0x0000060: 1b3a 0919 0612 0204 bd00 0e59 0312 0853
    0x0000070: b600 1b3a 0a19 0612 0204 bd00 0e59 0312
    0x0000080: 1153 b600 1b3a 0b19 07b8 001a 4c19 08b8
    0x0000090: 001a 4d19 09b8 001a 4e19 0ab8 001a 3a04
    0x00000a0: 190b b800 1a3a 052a 0604 54a7 000e 3a06
    0x00000b0: 1906 b800 182a 0704 542b b300 122c b300
    0x00000c0: 132d b300 1419 04b3 0015 1905 b300 162a
    0x00000d0: 0804 54b1                              
  Exception Handler Table:
    bci [30, 167] => handler: 174`

**Comment by alex-dubrouski** [comment]
Fixed by PR #8 and verified
